package com.codegen.model;
// Generated May 26, 2018 2:32:35 PM by Hibernate Tools 4.3.1
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * PlayerBankDetails generated by hbm2java
 */
@Entity
@Table(name = "player_bank_details")
public class PlayerBankDetails  implements Serializable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int id;

    @Column(name = "player_Id")
    private int playerId;
    
    @Column(name = "bank_Name")
    private String bankName;
    
    @Column(name = "available_Balance")
    private double availableBalance;
             
    @Column(name = "is_Active")
    private boolean isActive;

    @Column(name = "active_Date")
    private Date activeDate;

    public PlayerBankDetails() {
    }

    public PlayerBankDetails(int playerId, String bankName, double availableBalance, boolean isActive, Date activeDate) {
       this.playerId = playerId;
       this.bankName = bankName;
       this.availableBalance = availableBalance;
       this.isActive = isActive;
       this.activeDate = activeDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPlayerId() {
        return this.playerId;
    }
    
    public void setPlayerId(int playerId) {
        this.playerId = playerId;
    }
    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }
   
    public double getAvailableBalance() {
        return this.availableBalance;
    }
    
    public void setAvailableBalance(double availableBalance) {
        this.availableBalance = availableBalance;
    }
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }
       
    public Date getActiveDate() {
        return this.activeDate;
    }
    
    public void setActiveDate(Date activeDate) {
        this.activeDate = activeDate;
    }
    
}


